# Creat by Abraão Silva
# # Date 12 Nov 2018 
version: '3'
services:
  docker-jenkins: # JENKINS LATEST
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000 
    volumes:
      - "$PWD/jenkins-data:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/bin/zip:/usr/bin/zip
#      - /usr/bin/unzip:/usr/bin/unzip
#      - /usr/bin/mvn:/usr/bin/mvn
    environment:
      TZ: America/Sao_Paulo
      JAVA_OPTS: "-Xmx8192m"
